# Generated by Django 4.2.2 on 2023-06-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_autor_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='Autor',
        ),
        migrations.AddField(
            model_name='post',
            name='Contenido',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='Titulo',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
